.github/workflows/hugo-ci-workflow.yml
=> updated workflow

net/release-notes/_index.md, net/release-notes/release-notes-2021/_index.md, net/release-notes/release-notes-2021/aspose-pdf-for-net-21-4-release-notes/_index.md
=> PDFNET-49711 Publish release notes for 21.4

net/release-notes/release-notes-2021/_index.md, net/release-notes/release-notes-2021/aspose-pdf-for-net-21-5-release-notes/_index.md
=> Docs review for Aspose.PDF 21.5

net/advanced-operations/working-with-forms/acroforms/_index.md, net/advanced-operations/working-with-forms/acroforms/export-import-json/_index.md, net/whatsnew/_index.md, net/working-with-facades/form/import-and-export-data/_index.md, net/working-with-facades/form/whats-the-difference-between-xml-fdf-and-xfdf/_index.md
* update working with Forms section
* Update net/working-with-facades/form/whats-the-difference-between-xml-fdf-and-xfdf/_index.md
* fix code snippets
* fix: updated articles
---------
=> docs: updated Working with Forms section (#263)

python-java/_index.md, python-java/advanced-operations/forms/_index.md, python-java/advanced-operations/working-with-documents/add-toc-to-existing-pdf-in-python/_index.md, python-java/advanced-operations/working-with-documents/adding-javascript-in-python/_index.md, python-java/advanced-operations/working-with-documents/get-document-window-and-page-display-properties-in-python/_index.md, python-java/advanced-operations/working-with-pages/concatenate-pdf-files-in-python/_index.md, python-java/advanced-operations/working-with-pages/delete-a-particular-page-from-the-pdf-file-in-python/_index.md, python-java/advanced-operations/working-with-pages/get-a-particular-page-in-a-pdf-file-in-python/_index.md, python-java/advanced-operations/working-with-text/add-html-string-using-dom-in-python/_index.md, python-java/advanced-operations/working-with-text/add-text-to-an-existing-pdf-file-in-python/_index.md, python-java/advanced-operations/working-with-text/extract-text-from-all-the-pages-of-a-pdf-document-in-python/_index.md, python-java/get-started/_index.md, python-java/get-started/basics-of-dom-api/index.md, python-java/get-started/download-and-configure-aspose-pdf-in-python/_index.md
first update for python-java section
=> fix: fixed python-java section

net/whatsnew/_index.md
Add "What's new in Aspose.PDF 24.9"
=> Add "What's new in Aspose.PDF 24.9"

net/get-started/licensing/_index.md, net/get-started/supported-file-formats/_index.md
- "Licensing and limitations" updated.
- "Supported File Formats" updated.
=> "Licensing and limitations", "Supported File Formats" - updated

net/whatsnew/_index.md
Add "What’s new in Aspose.PDF" for v.24.10
=> Add "What’s new in Aspose.PDF" for v.24.10

net/advanced-operations/annotations/add-delete-and-get-annotation/text-annotations/_index.md
fix: add csharp open close brackets
=> Update ToC (PDFNET-58672)

net/whatsnew/_index.md
Whats new - fix samples - Part #1
=> Whats new - fix samples - Part #1

.github/workflows/pdf-prod.yml
=> Pull origin master branch

en/net/other-programming-languages/integration-with-aspose-total-components/convert-pdf-pages-to-images-and-recognize-barcodes/_index.md
=> Fix issues with Miscellaneous folder

en/net/get-started/installation/_index.md, en/net/other-programming-languages/integration-with-aspose-total-components/convert-pdf-pages-to-images-and-recognize-barcodes/_index.md
=> Fix issues with Misc folder

en/net/converting/convert-pdf-to-other-files/_index.md, en/net/get-started/advanced-features/_index.md, en/net/working-with-facades/form/identifying-form-fields-names/_index.md, en/net/working-with-facades/form/justify-text-in-a-textbox-field/_index.md, en/net/working-with-facades/formeditor/move-remove-form-field/_index.md
Updated code snippets for following articles:
- Identify form fields names
- Justify text in a textbox field
- Move/remove form field
- Advanced features
=> Updated code snippets for following articles:

en/net/advanced-operations/working-with-text/floating-box/_index.md
Update for FloatingBox descr in accordance changes maked for PDFNET-57610 (Positioning support)
=> Update for FloatingBox descr in accordance to PDFNET-57610 changes

en/net/advanced-operations/working-with-documents/working-with-layers/_index.md, en/net/advanced-operations/working-with-forms/acroforms/remove-form/_index.md, en/net/converting/convert-pdf-to-html/_index.md, en/net/whatsnew/_index.md
Add 24.12, 25.1 info. Fix code samples: Part #1.
Minor fixes.
=> Add 24.12, 25.1 info. Fix code samples: Part #1.

en/net/whatsnew/_index.md
=> Fix code samples: Part #2.

en/net/advanced-operations/securing-and-signing/_index.md, en/net/advanced-operations/securing-and-signing/digitally-sign-pdf-file/_index.md, en/net/advanced-operations/securing-and-signing/extract-signature-info/_index.md, en/net/advanced-operations/securing-and-signing/sign-pdf-document-from-smart-card/_index.md, en/net/other-programming-languages/choose-the-platform-and-interoperability-technology/_index.md, en/net/other-programming-languages/use-aspose-pdf-for-net-via-com-interop/_index.md
Update the interoperability section.
Minor fixes in the securing-and-signing.
=> Update the interoperability section

en/net/converting/_index.md, en/net/converting/convert-pdf-to-pdfx/_index.md
This commit adds PDF to PDF/X conversion documentation page and PDF to PDF/X-4 conversion with an external ICC profile example. It describes changes that are scheduled to deliver in the Aspose.PDF 25.2 version - please don't merge it befor its release.
=> Add PDF to PDF/X-4 conversion description (PDFNET-56954)

ar/net/advanced-operations/pdf-file-metadata/_index.md, en/net/advanced-operations/pdf-file-metadata/_index.md, es/net/advanced-operations/pdf-file-metadata/_index.md, fr/net/advanced-operations/pdf-file-metadata/_index.md, id/net/advanced-operations/pdf-file-metadata/_index.md, ja/net/advanced-operations/pdf-file-metadata/_index.md, ko/net/advanced-operations/pdf-file-metadata/_index.md, pt/net/advanced-operations/pdf-file-metadata/_index.md, ru/net/advanced-operations/pdf-file-metadata/_index.md, zh/net/advanced-operations/pdf-file-metadata/_index.md
=> PDFNET-51892 Add custom timezone in metadata
